"""
Django settings for dzdp project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os
from pathlib import Path
from django.conf.urls import url, include
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9#b%y#(nn6z#@7ozez!pl-gj-y0@!w$^p(o-oi$7&g*pl%h^ul'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dzdp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dzdp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bysj',  # 数据库名字
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1',  # 那台机器安装了MySQL
        'PORT': 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]

# 修改首页设置, 指向新创建的控制面板
# SIMPLEUI_HOME_PAGE = '/app/shouye/'
# SIMPLEUI_HOME_TITLE = '股票分析系统欢迎你'
# SIMPLEUI_HOME_ICON = 'fa fa-eye'
# logo 图
SIMPLEUI_LOGO = 'https://app.trendsi.com/img/projName@2x.1afe1844.png'

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 设置默认主题，指向主题css文件名。Element-ui风格
# SIMPLEUI_DEFAULT_THEME = 'element.css'

# 隐藏首页的快捷操作和最近动作
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True

# 修改左侧菜单首页设置
SIMPLEUI_HOME_TITLE = '股票分析系统欢迎你!'  # 首页标题<i class="fa-thin fa-bars"></i>
SIMPLEUI_HOME_ICON = 'fa fa-code'  # 首页图标

# 设置右上角Home图标跳转链接，会以另外一个窗口打开
# SIMPLEUI_INDEX = 'http://10.30.0.147:8080'

# 中文
LANGUAGE_CODE = 'zh-hans'
# 时区
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True
USE_L10N = True
USE_TZ = False
SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': True,
    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['数据展示', 'bar图展示','Pie图展示', 'Radar图展示','scatter图展示','echarts图标展示','权限认证'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': True,
    'menus': [
        {'name': '数据展示',
         'icon': 'fa fa-desktop',
         'models': [{
             'name': '股票数据',
             'icon': 'far fa-surprise',
             'url': '/admin/app/food/'
         }]
         },
        {'name': 'bar图展示',
         'icon': 'fas fa-user-shield',
         'models': [{
             'name': 'bar',
             'icon': 'fa fa-user',
             'url': 'http://127.0.0.1:8000/app/bar'
             # 'newTab': False,#跳转到新页面
         }]
         },
        {'name': 'Pie图展示',
         'icon': 'fas fa-user-shield',
         'models': [{
             'name': 'Pie',
             'icon': 'fa fa-user',
             'url': 'http://127.0.0.1:8000/app/Pie'
             # 'newTab': False,#跳转到新页面
         }]
         },
        {'name': 'Radar图展示',
         'icon': 'fas fa-user-shield',
         'models': [{
             'name': 'Radar',
             'icon': 'fa fa-user',
             'url': 'http://127.0.0.1:8000/app/Radar'
             # 'newTab': False,#跳转到新页面
         }]
         },
        {'name': 'scatter图展示',
         'icon': 'fas fa-user-shield',
         'models': [{
             'name': 'scatter',
             'icon': 'fa fa-user',
             'url': 'http://127.0.0.1:8000/app/scatter'
             # 'newTab': False,#跳转到新页面
         }]
         },
        {'name': 'echarts图标展示',
                 'icon': 'fa fa-desktop',
                 'models': [{
                     'name': 'echarts图标',
                     'icon': 'far fa-surprise',
                     'url': 'http://127.0.0.1:8000/app/echartstubiao'
                 }]
                 },
        {
            'app': 'auth',
            'name': '权限认证',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fa fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fa fa-th-list',
                    'url': 'auth/group/'
                }
            ]
        },
    ]
}
